### PR TITLE
Add built-in console command list

### PR DESCRIPTION
**Pull request by aistis-**

### CODE REVIEW

**Comment by ThomasBerends** [comment]
Can this list also be found in the Symfony documentation somewhere? I would prefer to just keep links here and not have the actual contents.

**Comment by aistis-** [comment]
It is not, I had to download Symfony Standard Edition 3.0 to list the commands myself.

However, I know, that the exam contains questions related to the native commands (at least debug, lint). Unfortunately, some of them are not even mentioned in the symfony docs, or just have a few words. I believe, it is nice to have this list in one place.

We could create a separate .md page for the list. That's how we could keep the links :)

**Comment by ThomasBerends** [comment]
List would also display 'not so great' on the website. I agree that this list has to be available somewhere though, but maybe the Symfony docs are better for this. I'll follow up on this.

**Comment by ThomasBerends** [comment]
I've had contact about this, but unfortunately nothing has come out of it. I'm gonna close this pull request to clean up before I'm pushing the 4.0 certification list.

**Pull request closed without merging**
