### PR TITLE
Added links to "Controllers" and "Routing" topics

### PR DESCRIPTION
**Pull request by cristi-contiu**
This is the only reference to a built-in controller I could find in the Symfony Docs.

### CODE REVIEW

**Comment by ThomasBerends** [comment]
Hey, I didn't know this yet! Thanks for the pull request!

**Comment by cristi-contiu** [comment]
Also added a special attributes link to "Routing" topic.

**Comment by cristi-contiu** [comment]
Apart from the TemplateController, I think the RedirectController is the only other built-in internal controller available in Symfony, so it deserves a link in the Controllers topic.

**Comment by ThomasBerends** [comment]
Thanks for this. This is all awesome stuff. Thanks for expanding the list!

**Pull request merged**
