### PR TITLE
feat(all-topics): update links to 7.0

### PR DESCRIPTION
**Pull request by Sarah-eit**
# Adjustments

There are links to correct.

For each theme, I've listed the links to be changed and suggested a correction below.

## File : automated-tests.md

For your information, in the autamated-test.md file, there are 4 links that are no longer current.

These 4 links are still valid in versions below and including 5.0.

1. [Working with the Test Client - symfony.com](https://symfony.com/doc/6.0/testing.html#working-with-the-test-client)
2. [The Crawler - symfony.com](https://symfony.com/doc/6.0/testing.html#the-crawler)
3. [Accessing the Container - symfony.com](https://symfony.com/doc/6.0/testing.html#accessing-the-container)
4. [Testing Configuration - symfony.com](https://symfony.com/doc/6.0/testing.html#testing-configuration)

================

Link to be replaced :

1. [Working with the Test Client - symfony.com](https://symfony.com/doc/6.0/testing.html#working-with-the-test-client)

*https://symfony.com/doc/6.0/testing.html#working-with-the-test-client*

Could be replaced by :

=> https://symfony.com/doc/7.0/testing.html#making-requests

================

Link to be replaced :

1. [The Crawler - symfony.com](https://symfony.com/doc/6.0/testing.html#the-crawler)

*https://symfony.com/doc/6.0/testing.html#the-crawler*

Could be replaced by :

=> https://symfony.com/doc/7.0/testing.html#write-your-first-application-test

================

Link to be replaced :

3. [Accessing the Container - symfony.com](https://symfony.com/doc/6.0/testing.html#accessing-the-container)

*https://symfony.com/doc/6.0/testing.html#accessing-the-container*

Could be integrated into :

=> https://symfony.com/doc/7.0/testing.html#retrieving-services-in-the-test

================

Link to be replaced :

4. [Testing Configuration - symfony.com](https://symfony.com/doc/6.0/testing.html#testing-configuration)

*https://symfony.com/doc/6.0/testing.html#testing-configuration*

Could be replaced by :

=> https://symfony.com/doc/7.0/testing.html#set-up-your-test-environment

## File : http-caching.md

For your information, there is 1 link in the http-caching.md file that is no longer valid.

This link is still valid in versions lower than 4.0 inclusive.

1. [Caching Pages that Contain CSRF Protected Forms - symfony.com](https://symfony.com/doc/6.0/http_cache/form_csrf_caching.html)

================

Link to be replaced :

1. [Caching Pages that Contain CSRF Protected Forms - symfony.com](https://symfony.com/doc/6.0/http_cache/form_csrf_caching.html)

*https://symfony.com/doc/6.0/http_cache/form_csrf_caching.html*

Could be replaced by :

=> https://symfony.com/doc/7.0/security/csrf.html

================

## File : controllers.php

For your information, there are 2 links in the controllers.md file that are no longer valid.

These links are still valid in versions lower than 4.0 inclusive.

1. [Controller Naming Pattern - symfony.com](https://symfony.com/doc/6.0/routing.html#controller-naming-pattern)
2. [Flash Messages - symfony.com](https://symfony.com/doc/6.0/controller.html#flash-messages)

================

Link to be replaced :

1. [Controller Naming Pattern - symfony.com](https://symfony.com/doc/6.0/routing.html#controller-naming-pattern)

*https://symfony.com/doc/6.0/routing.html#controller-naming-pattern*

Could be replaced by :

=> https://symfony.com/doc/7.0/routing.html#creating-routes-in-yaml-xml-or-php-files

================

Link to be replaced :

2. [Flash Messages - symfony.com](https://symfony.com/doc/6.0/controller.html#flash-messages)

*https://symfony.com/doc/6.0/controller.html#flash-messages*

Could be integrated into :

=> https://symfony.com/doc/7.0/controller.html#managing-the-session

================

## File : miscellaneous.md

For your information, there is 1 link in the miscellaneous.md file that is not valid.

1. [Troubleshooting Problems - symfony.com](https://symfony.com/doc/6.0/the-fast-track/en/5-debug.html)

*https://symfony.com/doc/6.0/the-fast-track/en/5-debug.html*

================

Link to be replaced :

1. [Troubleshooting Problems - symfony.com](https://symfony.com/doc/6.0/the-fast-track/en/5-debug.html)

*https://symfony.com/doc/6.0/the-fast-track/en/5-debug.html*

Could be replaced by :

=> https://symfony.com/doc/current/the-fast-track/en/5-debug.html

================

## File : templating-with-twig.md

For your information, in the templating-with-twig.md file, there are 2 links that are no longer valid.

These links are still valid in some lower versions.

1. [Pluralization](https://symfony.com/doc/6.0/translation/message_format.html#pluralization)
2. [How to Dump Debug Information in Twig Templates](https://symfony.com/doc/6.0/templating/debug.html)

================

Link to be replaced :

1. [Pluralization](https://symfony.com/doc/6.0/translation/message_format.html#pluralization)

*https://symfony.com/doc/6.0/translation/message_format.html#pluralization*

Could be integrated into :

=> https://symfony.com/doc/7.0/reference/formats/message_format.html#pluralization

================

Link to be replaced :

2. [How to Dump Debug Information in Twig Templates](https://symfony.com/doc/6.0/templating/debug.html)

*https://symfony.com/doc/6.0/templating/debug.html*

Could be replaced by :

=> https://symfony.com/doc/7.0/templates.html#the-dump-twig-utilities

================

## File : security.md

For your information, in the security.md file, there are 2 links that are no longer valid.

These links are still valid in some lower versions.

1. [Initial security.yml Setup (Authentication) - symfony.com](https://symfony.com/doc/6.0/security.html#initial-security-yml-setup-authentication)
2. [Encoding the User's Password - symfony.com](https://symfony.com/doc/6.0/security.html#c-encoding-the-user-s-password)

================

Link to be replaced :

1. [Initial security.yml Setup (Authentication) - symfony.com](https://symfony.com/doc/6.0/security.html#initial-security-yml-setup-authentication)

*https://symfony.com/doc/6.0/security.html#initial-security-yml-setup-authentication*

Could be integrated into (paragraphs to the next chapter) :

=> https://symfony.com/doc/7.0/security.html

================

Link to be replaced :

1. [Encoding the User's Password - symfony.com](https://symfony.com/doc/6.0/security.html#c-encoding-the-user-s-password)

*https://symfony.com/doc/6.0/security.html#c-encoding-the-user-s-password*

Could be replaced by (last half of the chapter) :

=> https://symfony.com/doc/7.0/security.html#registering-the-user-hashing-passwords

================

### CODE REVIEW

**Comment by ThomasBerends** [comment]
Wow! That's saving me quite some work. Was planning to do it this week so this saves up a lot of my time. Thank you!

Feel free to process the proposed replacements. It's common that some links to away or some get added for each version.

**Comment by Sarah-eit** [comment]
I'll make the replacements and then send the code to the current branch :+1:

**Comment by Sarah-eit** [comment]
@ThomasBerends  I sent the corrections :up:

**Comment by ThomasBerends** [comment]
Thanks! I'll await the Symfony 7 release and the release of the new certification, then I'll merge it.

Thank you for all this hard work. This is absolutely amazing!

**Comment by Sarah-eit** [comment]
You're welcome, it'll help with revision  :slightly_smiling_face:

**Comment by ThomasBerends** [comment]
Merged it, since in the Symfony Slack, Javier confirmed that the certfiication will be introduced in a few days.

Thanks for this hard work!

**Comment by Sarah-eit** [comment]
You're welcome  🙂

**Pull request merged**
