### PR TITLE
Add link group slack

### PR DESCRIPTION
**Pull request by eerison**
- add link in readme for join group slack

Issue #2

### CODE REVIEW

**Comment by eerison** [comment]
this link is the link of slack group!

**Comment by eerison** [comment]
@ThomasBerends do you can see this pull request?

**Comment by ThomasBerends** [comment]
Yes. Will check this out later (on mobile right now).

**Comment by ThomasBerends** [comment]
Hey. I've decided to add the link below the header instead of on top. So I've added the commit myself. I'll deny this one, but still, thanks for your help, and if you have any other additions, they are welcome as pull requests.

**Comment by eerison** [comment]
all right!

**Pull request closed without merging**
